# Generated by Django 6.0 on 2025-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vehicle_type', models.CharField(choices=[('SUV', 'Внедорожник'), ('PICKUP', 'Пикап')], max_length=10, verbose_name='Тип')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (чел.)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Изображение')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
